### ISSUE TITLE
历史记录问题

### ISSUE THREAD

**Issue by barood** [xunuoi/MO.Pjax#1]
你好问下为什么不能返回第一页，偶尔可以

**Comment by xunuoi** [comment]
@barood 能具体讲code和用例贴出来吗？

**Comment by fh-combo** [comment]
![image](https://user-images.githubusercontent.com/16040462/35143449-8cb7a0b6-fd3c-11e7-8683-39a52f0af9ec.png)
`<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
    <script type="text/javascript" src="./jquery.min.js"></script>
    <script type="text/javascript" src="./mo.pjax.es5.js"></script>
</head>

<body>
    <div class="ctn">
        <h3>Test Mo.pjax</h3>
        <p>
            <a href="about.html">About</a>
            <a href="toxic.html">Toxic</a>
        </p>
    </div>
    <div id="ttt" style="margin-top: 30px;">
        <p>This is index html</p>
    </div>

    <script>
        MO.go('.ctn a', '#ttt')
    </script>
</body>

</html>`

目录
![image](https://user-images.githubusercontent.com/16040462/35143471-a4323562-fd3c-11e7-908b-14b4ce8f9885.png)
为什么会这样，请问是怎么用的，pjax可不可以访问今天的html吗？
